# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/DigitalSystem/LAB4-Memory/LAB4-Memory.srcs/sources_1/ip/bram8x8/bram8x8.xci
# IP: The module: 'bram8x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/DigitalSystem/LAB4-Memory/LAB4-Memory.gen/sources_1/ip/bram8x8/bram8x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram8x8'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Xilinx/DigitalSystem/LAB4-Memory/LAB4-Memory.srcs/sources_1/ip/bram8x8/bram8x8.xci
# IP: The module: 'bram8x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/DigitalSystem/LAB4-Memory/LAB4-Memory.gen/sources_1/ip/bram8x8/bram8x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram8x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
